[package]
name = "streamlib"
version = "0.1.0"
authors = ["Yuval Adam <_@yuv.al>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
directories = "2.0.2"
duct = "0.13.0"
glob = "0.3.0"
serde = { version = "1.0.101", features = ["derive"] }
termion = "1.5.3"
toml = "0.5.3"
