[package]
name = "streamlib"
version = "0.1.0"
authors = ["Yuval Adam <_@yuv.al>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
