[package]
name = "streamlib"
version = "0.1.0"
authors = ["Yuval Adam <_@yuv.al>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
duct = "0.13.0"
termion = "1.5.3"
toml = "0.5.3"
serde = { version = "1.0.101", features = ["derive"] }
