[channel13]
url = "https://besttv1.aoslive.it.best-tv.com/reshet/studio/index.m3u8"
http_header = "Referer: https://besttv1.aoslive.it.best-tv.com/"

[aljazeera]
url = "http://aljazeera-eng-apple-live.adaptive.level3.net/apple/aljazeera/english/appleman.m3u8"

[groovesalad]
name = "Groove Salad"
description = "A nicely chilled plate of ambient/downtempo beats and grooves"
url = "http://somafm.com/groovesalad.pls"
tags = ["somafm", "radio", "ambient", "groove"]

[secretagent]
url = "http://somafm.com/secretagent.pls"
