[modiinindustry]
url = "https://5c328052cb7f5.streamlock.net/live/MODIININDUSTRY.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ohalim]
url = "https://5c328052cb7f5.streamlock.net/live/OHALIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ofakim]
url = "https://5c328052cb7f5.streamlock.net/live/OFAKIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[orakiva]
url = "https://5c328052cb7f5.streamlock.net/live/ORAKIVA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[achihod]
url = "https://5c328052cb7f5.streamlock.net/live/ACHIHOD.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ahisemech]
url = "https://5c328052cb7f5.streamlock.net/live/AHISEMECH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[alon]
url = "https://5c328052cb7f5.streamlock.net/live/ALON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[elishema]
url = "https://5c328052cb7f5.streamlock.net/live/ELISHEMA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[elal]
url = "https://5c328052cb7f5.streamlock.net/live/ELAL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[alfeimenashe]
url = "https://5c328052cb7f5.streamlock.net/live/ALFEIMENASHE.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[emhamoshavot]
url = "https://5c328052cb7f5.streamlock.net/live/EMHAMOSHAVOT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[emunim]
url = "https://5c328052cb7f5.streamlock.net/live/EMUNIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[eshelhanasi]
url = "https://5c328052cb7f5.streamlock.net/live/ESHELHANASI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beerganimprior]
url = "https://5c328052cb7f5.streamlock.net/live/BEERGANIMPRIOR.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[bialikhadera]
url = "https://5c328052cb7f5.streamlock.net/live/BIALIKHADERA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beitdagan]
url = "https://5c328052cb7f5.streamlock.net/live/BEITDAGAN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beityehoshua]
url = "https://5c328052cb7f5.streamlock.net/live/BEITYEHOSHUA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beitlid]
url = "https://5c328052cb7f5.streamlock.net/live/BEITLID.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beitraban]
url = "https://5c328052cb7f5.streamlock.net/live/BEITRABAN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beitshemesh]
url = "https://5c328052cb7f5.streamlock.net/live/BEITSHEMESH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[binyamina]
url = "https://5c328052cb7f5.streamlock.net/live/BINYAMINA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[baftistim]
url = "https://5c328052cb7f5.streamlock.net/live/BAFTISTIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[batzra]
url = "https://5c328052cb7f5.streamlock.net/live/BATZRA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[barilan]
url = "https://5c328052cb7f5.streamlock.net/live/BARILAN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[brachya]
url = "https://5c328052cb7f5.streamlock.net/live/BRACHYA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gvulut]
url = "https://5c328052cb7f5.streamlock.net/live/GVULUT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[givatshmuel]
url = "https://5c328052cb7f5.streamlock.net/live/GIVATSHMUEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[givati]
url = "https://5c328052cb7f5.streamlock.net/live/GIVATI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[geha]
url = "https://5c328052cb7f5.streamlock.net/live/GEHA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[goral]
url = "https://5c328052cb7f5.streamlock.net/live/GORAL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gilolong]
url = "https://5c328052cb7f5.streamlock.net/live/GILOLONG.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[giloshort]
url = "https://5c328052cb7f5.streamlock.net/live/GILOSHORT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gimzo]
url = "https://5c328052cb7f5.streamlock.net/live/GIMZO.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gilam]
url = "https://5c328052cb7f5.streamlock.net/live/GILAM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ganyavne]
url = "https://5c328052cb7f5.streamlock.net/live/GANYAVNE.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ganrave]
url = "https://5c328052cb7f5.streamlock.net/live/GANRAVE.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[jiser]
url = "https://5c328052cb7f5.streamlock.net/live/JISER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gesherhashalom]
url = "https://5c328052cb7f5.streamlock.net/live/GESHERHASHALOM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[davrat]
url = "https://5c328052cb7f5.streamlock.net/live/DAVRAT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[dganyaroad57]
url = "https://5c328052cb7f5.streamlock.net/live/DGANYAROAD57.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hadasim]
url = "https://5c328052cb7f5.streamlock.net/live/HADASIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hadarim]
url = "https://5c328052cb7f5.streamlock.net/live/HADARIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamovil]
url = "https://5c328052cb7f5.streamlock.net/live/HAMOVIL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamahtesh]
url = "https://5c328052cb7f5.streamlock.net/live/HAMAHTESH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamelaha]
url = "https://5c328052cb7f5.streamlock.net/live/HAMELAHA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hasargel]
url = "https://5c328052cb7f5.streamlock.net/live/HASARGEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[haogen]
url = "https://5c328052cb7f5.streamlock.net/live/HAOGEN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hakerach]
url = "https://5c328052cb7f5.streamlock.net/live/HAKERACH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hertzeliaeastroad531]
url = "https://5c328052cb7f5.streamlock.net/live/HERTZELIAEASTROAD531.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hashiva]
url = "https://5c328052cb7f5.streamlock.net/live/HASHIVA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[zichronyaakov]
url = "https://5c328052cb7f5.streamlock.net/live/ZICHRONYAAKOV.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[zarzir]
url = "https://5c328052cb7f5.streamlock.net/live/ZARZIR.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[havatshaarhagy]
url = "https://5c328052cb7f5.streamlock.net/live/HAVATSHAARHAGY.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[holot]
url = "https://5c328052cb7f5.streamlock.net/live/HOLOT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[horashim]
url = "https://5c328052cb7f5.streamlock.net/live/HORASHIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hativa7]
url = "https://5c328052cb7f5.streamlock.net/live/HATIVA7.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[henroad531]
url = "https://5c328052cb7f5.streamlock.net/live/HENROAD531.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hefer]
url = "https://5c328052cb7f5.streamlock.net/live/HEFER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hatzav]
url = "https://5c328052cb7f5.streamlock.net/live/HATZAV.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[tchernikhovsky]
url = "https://5c328052cb7f5.streamlock.net/live/TCHERNIKHOVSKY.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yasif]
url = "https://5c328052cb7f5.streamlock.net/live/YASIF.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yavne]
url = "https://5c328052cb7f5.streamlock.net/live/YAVNE.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yagel]
url = "https://5c328052cb7f5.streamlock.net/live/YAGEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yadmordehi]
url = "https://5c328052cb7f5.streamlock.net/live/YADMORDEHI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yaarhedera]
url = "https://5c328052cb7f5.streamlock.net/live/YAARHEDERA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yarkon]
url = "https://5c328052cb7f5.streamlock.net/live/YARKON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kabri]
url = "https://5c328052cb7f5.streamlock.net/live/KABRI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kokhavyair]
url = "https://5c328052cb7f5.streamlock.net/live/KOKHAVYAIR.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfarhroe]
url = "https://5c328052cb7f5.streamlock.net/live/KFARHROE.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfarsabaeast]
url = "https://5c328052cb7f5.streamlock.net/live/KFARSABAEAST.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfrakara]
url = "https://5c328052cb7f5.streamlock.net/live/KFRAKARA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfrashmariyahu]
url = "https://5c328052cb7f5.streamlock.net/live/KFRASHMARIYAHU.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfartavor]
url = "https://5c328052cb7f5.streamlock.net/live/KFARTAVOR.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kareynaamansouth]
url = "https://5c328052cb7f5.streamlock.net/live/KAREYNAAMANSOUTH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[karmielwest]
url = "https://5c328052cb7f5.streamlock.net/live/KARMIELWEST.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[karmielcenter]
url = "https://5c328052cb7f5.streamlock.net/live/KARMIELCENTER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[lahavkvish6]
url = "https://5c328052cb7f5.streamlock.net/live/LAHAVKVISH6.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[lod]
url = "https://5c328052cb7f5.streamlock.net/live/LOD.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[lapid]
url = "https://5c328052cb7f5.streamlock.net/live/LAPID.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[maahazkvish6]
url = "https://5c328052cb7f5.streamlock.net/live/MAAHAZKVISH6.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[migdaltzedek]
url = "https://5c328052cb7f5.streamlock.net/live/MIGDALTZEDEK.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[moran]
url = "https://5c328052cb7f5.streamlock.net/live/MORAN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[morasha]
url = "https://5c328052cb7f5.streamlock.net/live/MORASHA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mahanaim]
url = "https://5c328052cb7f5.streamlock.net/live/MAHANAIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[macabimreut]
url = "https://5c328052cb7f5.streamlock.net/live/MACABIMREUT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mesubim]
url = "https://5c328052cb7f5.streamlock.net/live/MESUBIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[maaganmichael]
url = "https://5c328052cb7f5.streamlock.net/live/MAAGANMICHAEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[matzlih]
url = "https://5c328052cb7f5.streamlock.net/live/MATZLIH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mitzpemodiin]
url = "https://5c328052cb7f5.streamlock.net/live/MITZPEMODIIN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mitkanadam]
url = "https://5c328052cb7f5.streamlock.net/live/MITKANADAM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahalhadera]
url = "https://5c328052cb7f5.streamlock.net/live/NAHALHADERA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahshonim]
url = "https://5c328052cb7f5.streamlock.net/live/NAHSHONIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nitzanim]
url = "https://5c328052cb7f5.streamlock.net/live/NITZANIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nirgalim]
url = "https://5c328052cb7f5.streamlock.net/live/NIRGALIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[namalashdod]
url = "https://5c328052cb7f5.streamlock.net/live/NAMALASHDOD.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[natbag]
url = "https://5c328052cb7f5.streamlock.net/live/NATBAG.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[netanya]
url = "https://5c328052cb7f5.streamlock.net/live/NETANYA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[savion]
url = "https://5c328052cb7f5.streamlock.net/live/SAVION.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[sgula]
url = "https://5c328052cb7f5.streamlock.net/live/SGULA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[silver]
url = "https://5c328052cb7f5.streamlock.net/live/SILVER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[sirkin]
url = "https://5c328052cb7f5.streamlock.net/live/SIRKIN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[adhalom]
url = "https://5c328052cb7f5.streamlock.net/live/ADHALOM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[adanim]
url = "https://5c328052cb7f5.streamlock.net/live/ADANIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[einhamifrtz]
url = "https://5c328052cb7f5.streamlock.net/live/EINHAMIFRTZ.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[eron]
url = "https://5c328052cb7f5.streamlock.net/live/ERON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[amiad]
url = "https://5c328052cb7f5.streamlock.net/live/AMIAD.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[arara]
url = "https://5c328052cb7f5.streamlock.net/live/ARARA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[atlit]
url = "https://5c328052cb7f5.streamlock.net/live/ATLIT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[parkafek]
url = "https://5c328052cb7f5.streamlock.net/live/PARKAFEK.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[palyam]
url = "https://5c328052cb7f5.streamlock.net/live/PALYAM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[pardasia]
url = "https://5c328052cb7f5.streamlock.net/live/PARDASIA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[tzrifin]
url = "https://5c328052cb7f5.streamlock.net/live/TZRIFIN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kadarim]
url = "https://5c328052cb7f5.streamlock.net/live/KADARIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kiryatatasouth]
url = "https://5c328052cb7f5.streamlock.net/live/KIRYATATASOUTH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[reem]
url = "https://5c328052cb7f5.streamlock.net/live/REEM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[regba]
url = "https://5c328052cb7f5.streamlock.net/live/REGBA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[rehovotwast]
url = "https://5c328052cb7f5.streamlock.net/live/REHOVOTWAST.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[rinatya]
url = "https://5c328052cb7f5.streamlock.net/live/RINATYA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[raanananorth]
url = "https://5c328052cb7f5.streamlock.net/live/RAANANANORTH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shoket]
url = "https://5c328052cb7f5.streamlock.net/live/SHOKET.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shimshon]
url = "https://5c328052cb7f5.streamlock.net/live/SHIMSHON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shaalabim]
url = "https://5c328052cb7f5.streamlock.net/live/SHAALABIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shaarhanegev]
url = "https://5c328052cb7f5.streamlock.net/live/SHAARHANEGEV.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shaariya]
url = "https://5c328052cb7f5.streamlock.net/live/SHAARIYA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shfeyah]
url = "https://5c328052cb7f5.streamlock.net/live/SHFEYAH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shfaim]
url = "https://5c328052cb7f5.streamlock.net/live/SHFAIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shapirim]
url = "https://5c328052cb7f5.streamlock.net/live/SHAPIRIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[sara]
url = "https://5c328052cb7f5.streamlock.net/live/SARA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[telarad]
url = "https://5c328052cb7f5.streamlock.net/live/TELARAD.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[taabura]
url = "https://5c328052cb7f5.streamlock.net/live/TAABURA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

