[kan11]
name = "Kan channel 11"
url = "https://kanlivep2event-i.akamaihd.net/hls/live/747610/747610/master.m3u8"

[kan-hinuhit]
name = "Kan hinuhit"
url = "https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/master.m3u8"

[channel13]
name = "Channel 13"
url = "https://besttv1.aoslive.it.best-tv.com/reshet/studio/index.m3u8"
http_headers = ["Referer: https://besttv1.aoslive.it.best-tv.com/"]

[knesset]
name = "Knesset channel 99"
url = "https://w1.013.gostreaming.tv/Knesset/myStream/playlist.m3u8"
