[channel13]
url = "https://besttv1.aoslive.it.best-tv.com/reshet/studio/index.m3u8"
http_headers = ["Referer: https://besttv1.aoslive.it.best-tv.com/"]

[aljazeera]
url = "http://aljazeera-eng-apple-live.adaptive.level3.net/apple/aljazeera/english/appleman.m3u8"
