name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            archive: tar
            binary: streamlib
            output: streamlib-${{ github.sha }}-x86_64-apple-darwin.tar.gz
            content_type: application/gzip
          - os: windows-latest
            archive: zip
            binary: streamlib.exe
            output: streamlib-${{ github.sha }}-x86_64-pc-windows-msvc.zip
            content_type: application/zip
          - os: ubuntu-latest
            archive: tar
            binary: streamlib
            output: streamlib-${{ github.sha }}-x86_64-unknown-linux-gnu.tar.gz
            content_type: application/gzip

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --verbose --release

      - name: Test
        run: cargo test --verbose

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: target/release/${{ matrix.binary }}
          path: ${{ matrix.output }}
