name: Test

on: [push]

runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [macOS-latest, windows-latest, ubuntu-latest]

jobs:
  build:
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
