name: Test

on: [push]

jobs:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [macOS-latest, windows-latest, ubuntu-latest]
  build:
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
