name: Test

on:
  push:
    branches:
      - '*'
    tags:
      - '!refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
